### ISSUE TITLE
SAML - Signature verification failed. Invalid document format.

### ISSUE THREAD

**Issue by jeganarepo** [jeremyschulman/netbox-plugin-auth-saml2#68]
I have followed the [](https://github.com/jeremyschulman/netbox-plugin-auth-saml2 ) page to configure the SSO using SAML2.0. 

Used remote_auth_backend as ` django3_saml2_nbplugin.backends.SAML2CustomAttrUserBackend`

Got the below error and attached screen shot. It seems like I am getting Netbox UI but not logged in. Can someone pls help me on this

<img width="1792" alt="Screenshot 2023-04-12 at 10 01 30 PM" src="https://user-images.githubusercontent.com/69963878/231793628-7d0e84d0-e7df-4040-8f03-78c3d0c5a39b.png">

**Comment by jeganarepo** [comment]
```
pluginsConfig:
  django3_saml2_nbplugin:
    AUTHENTICATION_BACKEND: REMOTE_AUTH_BACKEND
    ASSERTION_URL: https://abc.net
    ENTITY_ID: https://abc.net
    METADATA_AUTO_CONF_URL: <URL Of the Metadata>
    CUSTOM_ATTR_BACKEND:
      USERNAME_ATTR: email
      MAIL_ATTR: email
      FIRST_NAME_ATTR: firstName
      LAST_NAME_ATTR: lastName
      ALWAYS_UPDATE_USER: "True"
      GROUP_ATTR: groups
      FLAGS_BY_GROUP: 
        is_power_group: netbox-per-users
```
        
Enabled plugins

```
django3-auth-saml2
netbox-plugin-auth-saml2
apk add --no-cache xmlsec
```
